# Generated by Django 3.0.4 on 2020-06-03 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20200603_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_registo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
